# Basic parameters
baseURL: "https://blakeruprecht.com"
title: "Blake Ruprecht"
theme: "notebook"
enableRobotsTXT: true

params:
  math: true
  blog:
    toc: false
  logo: "/logo.png"

services:
  googleAnalytics:
    ID: 'G-3TL1K0T2Y4'

markup:
  tableOfContents:
    endLevel: 3
    ordered: false
    startLevel: 2
  goldmark:
    renderer:
      unsafe: true
    parser:
      attribute: true
    extensions:
      passthrough:
        enable: true
        delimiters:
          block: 
            - ["[", "]"]
            - ["$$", "$$"]
          inline: 
            - ["$", "$"]

# module:
#   imports:
#     - path: "github.com/milafrerichs/hugo-wikilinks"