# Basic parameters
baseURL: "https://blakeruprecht.com"
title: "Blake Ruprecht"
theme: "notebook"
enableRobotsTXT: true

menu:
  main:
    - identifier: "kiss"
      name: "KISS"
      url: "/KISS/"
      weight: 10
    - identifier: "archives"
      name: "Archives"
      url: "/archives/"
      weight: 20

params:
  math: true
  blog:
    toc: true

services:
  googleAnalytics:
    ID: 'G-3TL1K0T2Y4'

markup:
  tableOfContents:
    endLevel: 3
    ordered: false
    startLevel: 2
  goldmark:
    renderer:
      unsafe: true
    extensions:
      passthrough:
        enable: true
        delimiters:
          block: 
            - ["[", "]"]
            - ["$$", "$$"]
          inline: 
            - ["$", "$"]

# module:
#   imports:
#     - path: "github.com/milafrerichs/hugo-wikilinks"