# Basic parameters
baseURL = "https://blakeruprecht.github.io"
title = "Blake Ruprecht"
theme = "notebook"
description = "My personal website discussing open source artificial intelligence, deep ecology, and simple living."

[menu]
  [[menu.main]]
    identifier = "blog"
    name = "Blog"
    url = "/blog"
    weight = 10
