# Basic parameters
baseURL = "https://blakeruprecht.github.io"
title = "Blake Ruprecht"
theme = "notebook"
enableRobotsTXT = true

[menu]
  [[menu.main]]
    identifier = "blog"
    name = "Blog"
    url = "/blog"
    weight = 10

[services]
  [services.googleAnalytics]
    ID = 'G-3TL1K0T2Y4'
