# Basic parameters
baseURL = "https://blakeruprecht.github.io"
title = "blakeruprecht.github.io"
theme = "notebook"

[menu]
	[[menu.main]]
		identifier = "blog"
		name = "/blog"
		url = "/blog"
		weight = 10








