# Basic parameters
baseURL = "https://blakeruprecht.github.io"
title = "BlakeRuprecht"
theme = "notebook"
enableRobotsTXT = true

[menu]
  [[menu.main]]
    identifier = "ExpLog"
    name = "ExpLog"
    url = "/blog"
    weight = 10

[services]
  [services.googleAnalytics]
    ID = 'G-3TL1K0T2Y4'

[markup.goldmark.renderer]
  unsafe = true

[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['\[', '\]'], ['$$', '$$']]
          inline = [['\$', '\$']]
[params]
  math = true
