# Basic parameters
baseURL = "https://blakeruprecht.github.io"
title = "Blake Ruprecht"
theme = "notebook"

[menu]
  [[menu.main]]
    identifier = "blog"
    name = "/Blog"
    url = "/blog"
    weight = 10



